config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #READ

  #read all of the tasks
  get '/tasks', to: "tasks#index"

  #1st get the blank form
  get '/tasks/new', to: "tasks#new"

  #read one task
  get '/tasks/:id', to: "tasks#show", as: :task

  #CREATE

  #2nd save the form to the db
  post '/tasks', to: "tasks#create"

  #UPDATE

  #1st get the restaurant form
  get '/tasks/:id/edit', to: "tasks#edit", as: :edit

  #2nd send the info to the database
  patch '/tasks/:id', to: "tasks#update"

  #DESTROY
  delete '/tasks/:id', to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  validates :title, :details, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)

    ## when finish, redirect_to
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(edit_task_params)
    redirect_to tasks_path

    ## when finish, redirect_to
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path

    ## when finish, redirect_to
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def edit_task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Update your task</h1>
<%= simple_form_for @task  do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Task Manager</h1>
<% @tasks.each do |task| %>
  <!-- link_to "ANCHOR", path -->
  <h4><%= link_to task.title, task_path(task.id) %></h4>
  <p><%= task.details %></p>
  <p><%= task.completed %></p>
  <p><%= link_to "Remove this task", task_path(task.id), data: {confirm: "Are you sure?" }, method: :delete %></p>
<% end %>
<p><%= link_to "Add a new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= simple_form_for @task  do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<%= link_to "Back", tasks_path %> | <%= link_to "Edit", edit_path %>